[package]
name = "salvo-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Salvo is based on hyper & tokio
salvo = "0.35.0"
tokio = { version = "1", features = ["macros"] }
